### ISSUE TITLE
Windows x64 GUI not showing or loading FC information

### ISSUE THREAD

**Issue by pielie1** [fedorcomander/kissfc-chrome-gui#42]
This version has problems connecting to the FC, version 1.14 does fine.
The GUI connects but does not load any information on the screen.

Even different computers has mostly the same issue. It connects but no info....

**Comment by fedorcomander** [comment]
are u using FW 1.2 ?

**Comment by gotnull** [comment]
Can I ask why you implemented a firmware lock on 1.15.6?

**Comment by fedorcomander** [comment]
Painful step, but from now on it should be easier for compatible/not compatible guis/firmwares. Plus, i dont have to spent too much time to make it  backward compatibile.

**Comment by mfocht001** [comment]
The lock you implemented completely screwed my day up. When I put my machine away, it was tuned perfect. NOW, this complete bullshit lock. Your statement "have to spent too much time to make it backward compatibile" infuriates me. I was locked out of a $700 machine because of this. I couldn't check my failsafe or check my AUX settings to do a flight check. I am just amazed at this bold move after I spent a shitload of money on a KISS setup. Unbelievable. Once I managed to "update" my firmware again, MY PC does not even recognize the FC now.Complete bullshit to decide to LOCK this. KISS is supossed to be simple...This has become a tangled mess just like every other damn attempt by CF/BF and so on.

**Comment by gotnull** [comment]
@mfocht001 Take it easy. I agree with you that it's annoying, however there was a small mention about the FW lock as part of the release notes. I think that it should have been outlined a little better. Especially on the KISS Downloads page so as to educate people that don't really understand what a FW lock entails.

The main problem was that Google Chrome updates all of your extensions without warning. So everyone on 1.14 automatically got updated to 1.15.6.

I think that the the updated 1.15.6 GUI should have instructed people on how to go about moving forward given that the GUI was automatically updated.

**Comment by mfocht001** [comment]
You have to understand this. I am locked out of my quad. Yes, I am upset. At least with other configurators you can at least update the firmware. A small mention of this is not really acceptable. It has been winter here and I have not flown this machine. For someone who purchased this combo to KEEP IT SIMPLE, I would like to simply fly. There is always a time to break out the soldering iron and dig into some technical stuff.  Isn't this going against the very grain of the ideals of KISS? On top of that, how do I get this fixed? Like I said, this does not even connect or get recognized anymore by windows.........

**Comment by mfocht001** [comment]
I am able to use Dfuse to update to 1.2 but in the windows device manager, it just says unknown device and a popup stating that a USB device has malfunctioned... I would like to know a workaround so I can perhaps fly tomorrow.

**Comment by gotnull** [comment]
The issue you're having has nothing to do with KISS. If Windows can't connect to your FC it's a Windows issue and has nothing to do with KISS software or hardware.

Try and fix your driver issues in Windows first. I'd recommend maybe even trying a Mac if you have access to one. Rule out any possible issues with your OS before blaming anything else. I know that sounds harsh, but Windows has always been notorious for causing issues with USB hardware.

**Comment by mfocht001** [comment]
That was the first thing I did. However, if it connected before, enough for me to see that lock information, that would indicate the drivers were correct previous to the FW upgrade,then after the update to 1.2, it will not connect at all thoughts?

**Comment by gotnull** [comment]
Can you confirm that you have the 1.15.6 KISS GUI and that you're connected to the internet? After you've upgraded to v1.2 FC firmware activation is required again so ensure you're connected to the internet so this can happen successfully.

**Comment by mfocht001** [comment]
I just tried this. I have another flight controller pico blx. I connected the FC to my PC and it connected successfully to betaflight. I removed the USB, closed BF and opened KISS chrome gui and I get the error of a malfunctioning USB device. I unplugged/shut down KISS GUI then held the bootloader button and opened dfuse, I can see this as an available device in dfuse but after the FW update, I cannot get the KISS GUI to communicate with the KISS FC. Yes....I have internet connection.

An interesting observation is that in the KISS GUI, I accidentally had it connected to my pico blx FC and all of the sudden I noticed COM 16 available (obviously couldn't connect since BF FW) and not the usual single option of KISS WIFI.

**Comment by mfocht001** [comment]
oops, yes. I confirmed the chrome GUI is version 1.15.6

**Comment by gotnull** [comment]
It sounds like you've definitely got some issues relating to USB/Drivers in Windows. Like I originally said. It's best to resolve these or maybe even try on a different computer to rule out any issues.

**Comment by fedorcomander** [comment]
Use standalone guis. They will not auto update. Chrome app is EOL and will be discontinued.

**Comment by mfocht001** [comment]
Ok, I fixed it. The upgrade to 1.2 was not good I think. I tried several times in dfuse to reprogram and even verify, but my windows machine would not recognize the FC using 1.2. To fix it, I reverted to 1.03 and the Chrome app and the new standalone 64 bit version both now recognized the FC. I then re flashed with dfuse to 1.2 and BAM. It worked. I am guessing it was a bad/corrupt upgrade from 1.03 to 1.2.

**Comment by fedorcomander** [comment]
I think so. Well, anyways, happy u sorted it out. I dont like unhappy ppl :)

**Comment by mfocht001** [comment]
Sorry for the frustration. I obviously quickly assumed an upgrade bug since the problem presented itself directly after the upgrade and after several attempts to reflash and verify. Anyway, the quad was quickly back to flying perfect with near stock PIDS and settings. Thanks for your hard work.

**Comment by jasonmvt** [comment]
hello, I found this thread when I ran into this problem.  I haven't updated my fc in ages so I went into the GUI and it told me my FW was obsolete.  so I downloaded the latest FW, read through the documentation, and proceeded to flash the fc ( after the usual screwing around with drivers for 2 hours on a windows 10 machine)  now it connects to the GUI but like others here I cant access the fc.
is there a work around for this yet? or do I have to use an older gui?

**Comment by rawbb203** [comment]
You have to read the notes in the bundle package of latest kiss firmware must match firmware and GUI must match GUI.

**Comment by jasonmvt** [comment]
thanks but i have the latest Gui and the latest firmware on the board....

**Comment by gotnull** [comment]
@jasonmvt What's the latest GUI version installed?

**Comment by jasonmvt** [comment]
I have the chrome version 1.15.8 


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Fulvio Cusumano <notifications@github.com> Date: 2017-08-30  3:54 AM  (GMT-08:00) To: fedorcomander/kissfc-chrome-gui <kissfc-chrome-gui@noreply.github.com> Cc: jasonmvt <vantoljason@gmail.com>, Mention <mention@noreply.github.com> Subject: Re: [fedorcomander/kissfc-chrome-gui] Windows x64 GUI not showing or loading FC information (#42) 
@jasonmvt What's the latest GUI version installed?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/fedorcomander/kissfc-chrome-gui","title":"fedorcomander/kissfc-chrome-gui","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/fedorcomander/kissfc-chrome-gui"}},"updates":{"snippets":[{"icon":"PERSON","message":"@gotnull in #42: @jasonmvt What's the latest GUI version installed?"}],"action":{"name":"View Issue","url":"https://github.com/fedorcomander/kissfc-chrome-gui/issues/42#issuecomment-325955691"}}}

**Comment by mfocht001** [comment]
I ran into this same problem. It was really annoying. The standalone did the trick. The Chrome app did not work with this  lock/obsolete nonsense. Since you mentioned that this is a windows 10 machine. I am assuming you have a 64 bit OS/CPU. [Here](http://kiss.flyduino.net/download/kiss-gui-v1-14-win64-standalone-version/)...This got me flying again.

**Comment by jasonmvt** [comment]
Thanks alot man!! I almost installed the stand alone  I'll try it tonight.   But still the dud driver and the regular driver continue to screw me every time lol


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: mfocht001 <notifications@github.com> Date: 2017-08-30  1:17 PM  (GMT-08:00) To: fedorcomander/kissfc-chrome-gui <kissfc-chrome-gui@noreply.github.com> Cc: jasonmvt <vantoljason@gmail.com>, Mention <mention@noreply.github.com> Subject: Re: [fedorcomander/kissfc-chrome-gui] Windows x64 GUI not showing or loading FC information (#42) 
I ran into this same problem. It was really annoying. The standalone did the trick. The Chrome app did not work with this  lock/obsolete nonsense. Since you mentioned that this is a windows 10 machine. I am assuming you have a 64 bit OS/CPU. Here...This got me flying again.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/fedorcomander/kissfc-chrome-gui","title":"fedorcomander/kissfc-chrome-gui","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/fedorcomander/kissfc-chrome-gui"}},"updates":{"snippets":[{"icon":"PERSON","message":"@mfocht001 in #42: I ran into this same problem. It was really annoying. The standalone did the trick. The Chrome app did not work with this  lock/obsolete nonsense. Since you mentioned that this is a windows 10 machine. I am assuming you have a 64 bit OS/CPU. [Here](http://kiss.flyduino.net/download/kiss-gui-v1-14-win64-standalone-version/)...This got me flying again."}],"action":{"name":"View Issue","url":"https://github.com/fedorcomander/kissfc-chrome-gui/issues/42#issuecomment-326106497"}}}

**Comment by mfocht001** [comment]
Cool! Notice my post below from a few months ago. I think there may be a bug in the upgrade process from the chrome GUI. You may have to go back to 1.3 if it doesn't work . But, it sounds like you have access to the GUI now..Just remember if it doesn't work with the standalone. Flash back 1.3 then upgrade to 1.2 from the standalone. Good Luck!

> Ok, I fixed it. The upgrade to 1.2 was not good I think. I tried several times in dfuse to reprogram and even verify, but my windows machine would not recognize the FC using 1.2. To fix it, I reverted to 1.03 and the Chrome app and the new standalone 64 bit version both now recognized the FC. I then re flashed with dfuse to 1.2 and BAM. It worked. I am guessing it was a bad/corrupt upgrade from 1.03 to 1.2.

>

**Comment by jasonmvt** [comment]
Well, nothing works, I tried that 1.14 gui, then finally figured out the dfu driver issue.  So I used dfuse to flash fc back to 1.3rc10 and connected to 1.14 gui, and I still can't access the tabs.  But it connects perfectly.


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: mfocht001 <notifications@github.com> Date: 2017-08-30  1:29 PM  (GMT-08:00) To: fedorcomander/kissfc-chrome-gui <kissfc-chrome-gui@noreply.github.com> Cc: jasonmvt <vantoljason@gmail.com>, Mention <mention@noreply.github.com> Subject: Re: [fedorcomander/kissfc-chrome-gui] Windows x64 GUI not showing or loading FC information (#42) 
Cool! Notice my post below from a few months ago. I think there may be a bug in the upgrade process from the chrome GUI. You may have to go back to 1.3 if it doesn't work . But, it sounds like you have access to the GUI now..Just remember if it doesn't work with the standalone. Flash back 1.3 then upgrade to 1.2 from the standalone. Good Luck!

Ok, I fixed it. The upgrade to 1.2 was not good I think. I tried several times in dfuse to reprogram and even verify, but my windows machine would not recognize the FC using 1.2. To fix it, I reverted to 1.03 and the Chrome app and the new standalone 64 bit version both now recognized the FC. I then re flashed with dfuse to 1.2 and BAM. It worked. I am guessing it was a bad/corrupt upgrade from 1.03 to 1.2.




—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/fedorcomander/kissfc-chrome-gui","title":"fedorcomander/kissfc-chrome-gui","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/fedorcomander/kissfc-chrome-gui"}},"updates":{"snippets":[{"icon":"PERSON","message":"@mfocht001 in #42: Cool! Notice my post below from a few months ago. I think there may be a bug in the upgrade process from the chrome GUI. You may have to go back to 1.3 if it doesn't work . But, it sounds like you have access to the GUI now..Just remember if it doesn't work with the standalone. Flash back 1.3 then upgrade to 1.2 from the standalone. Good Luck!\r\n\r\n\u003e Ok, I fixed it. The upgrade to 1.2 was not good I think. I tried several times in dfuse to reprogram and even verify, but my windows machine would not recognize the FC using 1.2. To fix it, I reverted to 1.03 and the Chrome app and the new standalone 64 bit version both now recognized the FC. I then re flashed with dfuse to 1.2 and BAM. It worked. I am guessing it was a bad/corrupt upgrade from 1.03 to 1.2.\r\n\r\n\u003e "}],"action":{"name":"View Issue","url":"https://github.com/fedorcomander/kissfc-chrome-gui/issues/42#issuecomment-326109608"}}}

**Comment by mfocht001** [comment]
Try moving back up to 1.2 from 1.03. I don't think 1.03 is supported in the new GUI. Convoluted and not in the spirited of "keeping it simple".

**Comment by jasonmvt** [comment]
Nice, just before I read your reply, I tried 1.2 and it worked on the 1.14 gui! It's back!!  Thanks for all the help and your time.Now how do I properly upgrade to the newest FW and gui without it locking up again?


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: mfocht001 <notifications@github.com> Date: 2017-08-30  6:06 PM  (GMT-08:00) To: fedorcomander/kissfc-chrome-gui <kissfc-chrome-gui@noreply.github.com> Cc: jasonmvt <vantoljason@gmail.com>, Mention <mention@noreply.github.com> Subject: Re: [fedorcomander/kissfc-chrome-gui] Windows x64 GUI not showing or loading FC information (#42) 
Try moving back up to 1.2 from 1.03. I don't think 1.03 is supported in the new GUI. Convoluted and not in the spirited of "keeping it simple".

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/fedorcomander/kissfc-chrome-gui","title":"fedorcomander/kissfc-chrome-gui","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/fedorcomander/kissfc-chrome-gui"}},"updates":{"snippets":[{"icon":"PERSON","message":"@mfocht001 in #42: Try moving back up to 1.2 from 1.03. I don't think 1.03 is supported in the new GUI. Convoluted and not in the spirited of \"keeping it simple\".\r\n"}],"action":{"name":"View Issue","url":"https://github.com/fedorcomander/kissfc-chrome-gui/issues/42#issuecomment-326160450"}}}

**Comment by mfocht001** [comment]
I think, it should be very simple to upgrade now only using the GUI. I think.Not 100 percent.

**Comment by jasonmvt** [comment]
But use which gui? The latest stand alone from the flyduino site?


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: mfocht001 <notifications@github.com> Date: 2017-08-30  6:54 PM  (GMT-08:00) To: fedorcomander/kissfc-chrome-gui <kissfc-chrome-gui@noreply.github.com> Cc: jasonmvt <vantoljason@gmail.com>, Mention <mention@noreply.github.com> Subject: Re: [fedorcomander/kissfc-chrome-gui] Windows x64 GUI not showing or loading FC information (#42) 
I think, it should be very simple to upgrade now only using the GUI. I think.Not 100 percent.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/fedorcomander/kissfc-chrome-gui","title":"fedorcomander/kissfc-chrome-gui","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/fedorcomander/kissfc-chrome-gui"}},"updates":{"snippets":[{"icon":"PERSON","message":"@mfocht001 in #42: I think, it should be very simple to upgrade now only using the GUI. I think.Not 100 percent."}],"action":{"name":"View Issue","url":"https://github.com/fedorcomander/kissfc-chrome-gui/issues/42#issuecomment-326166933"}}}

**Comment by mfocht001** [comment]
Yes. The Chrome app is no longer supported.

**Comment by jasonmvt** [comment]
Ok success!!! Latest gui and FW installed! Even flashed the esc's to latest as well.
Prob is my rear 2 esc's arm and beep but fail to stay lit. And won't arm.  I thought the flash might help but nope.


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: mfocht001 <notifications@github.com> Date: 2017-08-30  7:24 PM  (GMT-08:00) To: fedorcomander/kissfc-chrome-gui <kissfc-chrome-gui@noreply.github.com> Cc: jasonmvt <vantoljason@gmail.com>, Mention <mention@noreply.github.com> Subject: Re: [fedorcomander/kissfc-chrome-gui] Windows x64 GUI not showing or loading FC information (#42) 
Yes. The Chrome app is no longer supported.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/fedorcomander/kissfc-chrome-gui","title":"fedorcomander/kissfc-chrome-gui","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/fedorcomander/kissfc-chrome-gui"}},"updates":{"snippets":[{"icon":"PERSON","message":"@mfocht001 in #42: Yes. The Chrome app is no longer supported."}],"action":{"name":"View Issue","url":"https://github.com/fedorcomander/kissfc-chrome-gui/issues/42#issuecomment-326171097"}}}

**Comment by fedorcomander** [comment]
use LATEST (1.16.14) gui. it supports 1.2 and 1.3 firmwares.

**Comment by jasonmvt** [comment]
Yeah sweet thanks, I never knew there was versions even higher than the ones on the flyduino site.  I got everything going again thanks to this thread. Solved multiple problems last night.


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Alexander Fedorov <notifications@github.com> Date: 2017-08-30  10:59 PM  (GMT-08:00) To: fedorcomander/kissfc-chrome-gui <kissfc-chrome-gui@noreply.github.com> Cc: jasonmvt <vantoljason@gmail.com>, Mention <mention@noreply.github.com> Subject: Re: [fedorcomander/kissfc-chrome-gui] Windows x64 GUI not showing or loading FC information (#42) 
use LATEST (1.16.14) gui. it supports 1.2 and 1.3 firmwares.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/fedorcomander/kissfc-chrome-gui","title":"fedorcomander/kissfc-chrome-gui","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/fedorcomander/kissfc-chrome-gui"}},"updates":{"snippets":[{"icon":"PERSON","message":"@fedorcomander in #42: use LATEST (1.16.14) gui. it supports 1.2 and 1.3 firmwares. "}],"action":{"name":"View Issue","url":"https://github.com/fedorcomander/kissfc-chrome-gui/issues/42#issuecomment-326197973"}}}

**Comment by fedorcomander** [comment]
This is the place where changes are made, actually. 

Glad you sort out your things…

/Alex

**Comment by Jebadiaha** [comment]
I am running out of options and need help with connecting to the GUI. I can flash with DFuseDemo, but I get USB Device Not Recognized when trying to connect to the GUI.
 Here is the scenario:
Windows 7 64 bit
Several months ago I was able to flash software to KISS FC V1.  I was using v1.3RC30 and connecting with GUI 1.16.15.  Fast forward a few months (to 2 weeks ago) and I can still connect to GUI 1.16.15 with my original FC. 
I have a 2nd FC to setup.  New KISS FC V1 from GetFPV with KISS FCv1.2 installed.  Connected to the GUI and activated.  Then I flashed v1.3RC30 and could not connect to the GUI.   I get USB Device Not Recognized.  My original FC still connected to the GUI.
I uninstalled and reinstalled the STM Windows Driver and reflased Firmware v1.3RC30 and still could not connect to the GUI.  I tried GUI v1.15.6 also.
Tried another computer running windows 10. No luck with GUIs.
Tried uninstall and reinstall the STM Driver with computer restarts. No luck with GUIs.
Flashed KISS FC v1.2. No luck with GUIs.

Then I really screwed myself. To see if it was a problem with the KISS FC or the Windows computer, I experimented with my 1st FC that **does** connect to the GUI.
1st I made sure I could connect to the computer. It is FC 1.3RC30 and connected fine through GUI 1.16.15.
Then I flashed v1.3RC30 (the same version that was already on the FC), and now this FC board will not connect to the GUI!!!! WHAT!!!!!
I tried GUI 2.0.7.  No luck.
I uninstalled STM divers with computer shut down (and unplugged) combinations. No luck with GUI.
I installed DFuseDemo 3.0.6 (I was using 3.0.5) with several shut downds and install-uninstall-install of the com port drivers.
I down loaded STM 1.5.0 however there is no DfuSeDemo.exe program with that. Only STMFlashLoader Demo.exe which is different. So it did not work.
I tried different USB cables and USB ports.  No luck. I get USB Device Not Recognized
I am back to DFuseDemo 3.0.6 and now I can only connect to the 2nd FC in boot loader mode to flash the firmware.  My original FC will not even connect in boot loader mode.
AND still I cannot connect to any GUIs (1.15.6,  1.16.15, 2.0.7).  I get USB Device Not Recognized

I have an expensive paper weight at the moment and can't figure this out.  Does anyone have other suggestions?
As I understand it, the STM virtual comport driver is what the computer uses to connect to the FC with the GUI as well as DFuseDemo in bootloader mode.  So the driver works since I can connect in bootloader mode.  And there is not a KISS software compatibility issue with KISS FC versions and GUI versions.  At least this is what I think.

I really can't figure out what to do.  This does not make sense?

**Comment by Jebadiaha** [comment]
Would WiFi access be a good alternative/workaround?

**Comment by FerrisFPV** [comment]
I had the same problem.
The solution was to connect FC to the **USB 3.0** port

**Comment by zzfranczz** [comment]
How did you connect to USB 3.0 Port?

**Comment by rawbb203** [comment]
just keep trying. or ftdi tx rx ground

**Comment by zzfranczz** [comment]
After 6 hours of trying I finally got it to work.  do not ask me how or why, it just worked.  I was able to flash My FC to Firmware version: KISSFC-1.3RC10 and can use GUI KISS FC GUI: v2.0.13 to flash the ESC's but I still can not flash my FC using this GUI.  Any GUI before this one does not work and when I try to flash it to 1.3.34 using DFUSE it just bricks and I have to go back and start with FC FW 1.2 to get it back to working again.  This is not making things simple.  I am so far very disappointed with KISS products and the tools used to flash as well as the documentation of the tools and use.  I am thankful to the community who have made so many videos and posts otherwise I would be checking into a mental ward.  I wish I could figure out the steps it would take to flash my FC from where I am to the latest FW version but everything I try fails and there is no sense of consistency.  Also I noticed that the boot loader button only works partially.  I think the button maybe part of the issue as well.  I do not think it maintains contact even though it is pressed.  Jebadiaha, dude I feel your pain man.  I hope you figured things out.

**Comment by rawbb203** [comment]
can some one up there register these (virgin) mcu's for my kiss 24a esc?
need to generate hex files

**Comment by Jebadiaha** [comment]
Amen zzfrank. Fortunately some one on RC groups was kind enough to take me FC and flash it. It him a little bit. When I got it back I could connect to the gui and things were good. I fear if I try to change anything now that a few months have passed I will run into problems again. The FC is great but a more robust and reliable interface for firmware changes is needed. I am still overall very disappointed.

**Comment by zzfranczz** [comment]
The big reason I chose to build and use KISS was because I wanted to tinker and play.  But I am like you now afraid to make any changes which is counter to my desire to tinker and play with the settings and learn for the fear of not being able to set it back quickly.  I have used cleanFlight and betaflight and using my same computer have never had any issues as I have with KISS.  Honestly I have flashed hundreds of FC, TX & VX boards so I am not new to this process and have worked through dev nightmares.

**Comment by toomanytoys** [comment]
My KISS CC arrived today,
Windows7 x32. GUI not showing a new COM Port (device manager is saying #2 in the STM32 Virtual COM Port). PC is using COM 3, 5 and 6. The dropdown in the GUI shows, COM 3, 5, 6 and KISS WiFi, no #2 ? 
I have tried GUI v1.15.6.and v2.0.13 both don't show any new port when connecting the KISS CC
The device flashes in DFU mode OK, I tried KISSCC-1.3RC30 then went back to KISSCC-1.2 but
it's the same no new port appears. I then tried the Android app with OTG cable and it says the
device is not activated and shows the device number. But unfortunately that phone does not do
internet (no Data plan and not setup for data/internet either)
The Low Port number seems strange (#2) usually things I connect are COM7 or above, up to COM29.
In device manager I have previously changed Port numbers once or twice for other devices, but in
this case that option is unavailable in the properties, Advanced is not there.
I removed my wireless modem port 5 and 6, then only 3 shows, but 2 is still not shown in the GUI. 
If I've posted in the wrong place could you point me in the right direction, Thanks.

**Comment by Jebadiaha** [comment]
Try FC version 1.3RC34, and GUI 2.0.9. This is what worked for me last.

**Comment by zzfranczz** [comment]
I finally got it all to work.  The GUI that works for me is GUI_2.0.13.  I could not get the others to work.  They would see the com port but I could not access any of the tabs.  I was able to flash FC FW KISSFC-1.3-RC36c and then got the ESC's to flash properly.  I think the issue I had was that there was a driver conflict for the port.  The only thing I did was keep deleting the driver and the file and at some point after 2 hours it started working.  I have been able to login and flash and adjust the settings with no issue.  I fear that when I login into my betafight for my other frame that this will re-occur.

**Comment by toomanytoys** [comment]
Thanks Jebadiaha, it seems 1.3RC34 is not around currently. I can find CC-1.2, CC-1.3RC30,
CC-1.3RC33aa and CC-1.3RC36c dfu files and I was able to flash them all in DFU mode OK.
As for the GUI, I have GUI 1-15-6, GUI 1-16-15, GUI 2-0-6, GUI 2-0-8, GUI 2-0-9,  GUI 2-0-12 and
GUI 2-0-13. With the three firmwares and all of the GUI's above I still can't get a new port to appear
when plugging in the CC board, (Windows makes a USB connection sound OK), an STM32 Virtual COM port is present in Device manager (and working). But no New Port appears in the GUI.
All of that on a Win7, 32 bit PC.
I tried another Win7, 64 bit PC and got the same result, no new port appears in the GUI.
I tried a couple of USB cables just in case, same result.

Then I got out an original KISSFC v1.2, I flashed it the other day, and it works perfectly, no probs,
COM14 pops up instantly and it connects OK using the GUI's above.
When I use my android phone and the KISS App, OTG cable it tells me to activate the CC, it shows 
me the device ID number also. But that phone is not internet enabled so can't activate from there.

I can connect to Betaflight Config and DfuSe Demo (V3.0.6), VCP (V1.4.0) with several other types 
of FC without any problems, so I'm thinking my new KISSCC board may have a problem.
I can't really think of anything else to try.
I don't want to go down the Betaflight path.

**Comment by toomanytoys** [comment]
Hooray at Last ! !
I finally got my KISS CC (AIO) to work. The GUI (ver 2.0.13) finally detects a new COM# when I
plug in the CC board. Nothing was working, I tried several .dfu versions and several GUI versions
but nothing was working no new port was ever detected by the GUI. I'm running a Win7, 32 bit machine.
Even Flyduino support gave up on me after 13 e-mails.
So how did I do it ?
Simply used the Win8 COM Port driver, "dpinst_x86" and everything magically works.
COM24 pops up instantly on one CC board and COM25 on the other and now I have access
to both previously dead boards. Though it's still not working on my Android phone, pity.
Maybe this will help someone else having similar issues. Try a different OS, VCP driver.
